### PR TITLE
Deepsource transform 7930c238

### PR DESCRIPTION
**Pull request by johnsonjh**

### CODE REVIEW

**Comment by fpietrosanti** [comment]
Hey @johnsonjh ! Are you going to play with the VoIP wardialer? We really need to move foreward the DSP modem component in a more realiable way, want to have a conversation about that?

**Comment by johnsonjh** [comment]
Hey! @fpietrosanti 

Absolutely. It just might not be right away - I've got it earmarked to look at as part of a bigger project soon!

Sorry to (mistakenly) open the spammy pull request too!  I'm a bit OCD and today was repo cleanup today (with the help of some bots).

**Comment by fpietrosanti** [comment]
> Hey! @fpietrosanti
> 
> Absolutely. It just might not be right away - I've got it earmarked to look at as part of a bigger project soon!
> 
> Sorry to (mistakenly) open the spammy pull request too! I'm a bit OCD and today was repo cleanup today (with the help of some bots).

If you want to get in touch on Telegram or Twitter as @fpietrosanti i would love to bring back this conversion, as we might precisely go for a proper DSP integration logic within the Asterisk component, that's really the key aspects required, achieving a stable 1200/2400bps carrier that can operate with a lot of noise and frequency cut due to voip!

It is doable, with hardware modem over VoIP i can make 28.800, why can't we achieve that goal too?

**Comment by johnsonjh** [comment]
@fpietrosanti 

I'm usually on IRC... I'd have to figure out this "new" stuff :)

Anyway, yes, (stature of limitations expired now, I can talk!) I was actually scanning X.25 systems quite later than most would expect, usually in other countries that the US wasn't friendly with... but the most success was with an VoIP-ATA, G.711 forced, with a USR Courier v.Everything modem, often getting usable connections with very bad links. The ZyXEL (professional) series of modems worked well, as did Telebit, while many others did not.

I'd have to do some research into a good softmodem solution.  For the purposes of (VoIP) wardialing, you really only need to get a banner, of course, but a software modem that would be as reliable as a real one would be something extremely valuable.

I'm really outdated as to what would work here. I've not talked to Beave in a long time, but, I know that [iWar](https://github.com/beave/iwar) used to support IAX2 and IAXMODEM, but it never worked all that well. There is an [iWar2](https://github.com/beave/iwar2) that hasn't been touched in awhile.

Also, while it works passably for faxing, spandsp might not be a good option.. I never had it work well as a softmodem. More research is needed!

I appreciate your collection of X.25 things being put online, also!  There is of course a lot more out there (textfiles.com and such are good to look), but, I enjoyed seeing some things in your (Italian-centric) collection that I otherwise wouldn't have been aware of.  In the US it was all Sprintlink/TELENET, Tymnet, and sometimes Datapac (Canada) that we were exposed to. The CIS classic system used Sprintlink/TELNET for connectivity and to provide local dial-ins, and there was no shortage of (sometimes misconfigured) dialup PADs available in the late 1980's through the mid-1990's here.

While things are still in transition for re-hosting after a move and general unpleasantness that was 2020 for me - and not completely functioning as they should still - you should check out [BAN.AI](https://ban.ai). This has been a long-term project for me, but I've expanded the scope to simulate an X.25 network - well, not simulate, or even emulate, but, actually run a "real" one.

Perhaps I've made my task a bit too complex (because I have a few people interested but most are either disappointed by the current complexity of getting hooked up, or just genuinely baffled at the scope), but, I'm not just doing a "modern" network or even XOT, but instead, emulating the entire thing ... all the way down the leased-line wiring - and then hooking up some era correct systems.  This is running on a mix of real and emulated hardware and software.  

It's probably a bit underwhelming to see from the outside, because it really does so little for the amount of "stuff" [happening in the background](https://ban.ai/x25/BANNET-PRE1.png)... but, feel free to see the current state at of things at https://ban.ai/x25 - besides the web interface, the PAD is reachable by TELNET (connect.ban.ai port 2593), and SSH (pad@connect.ban.ai - and, since some mobile clients insist on a password, p@connect.ban.ai with password "pad").

(I should note, right now, the simulated 7094 is not online due to some serial flow control issues, and the NOC service is also a work in progress.)

**Pull request closed without merging**
